/**
 * wrap-client.mjs
 *
 * Wraps the esbuild-built CJS bundle (lib/client.cjs) into the DSH
 * __ModuleLoader__.load factory format that the web shell expects.
 *
 * DSH client modules are NOT plain ESM — they must be a single CJS factory
 * registered via window.__ModuleLoader__.load({ id, factory }). The factory
 * receives a `require` that resolves packages from the DSH seed table
 * (react, react/jsx-runtime, etc.). Everything else must be bundled in.
 *
 * Usage: node scripts/wrap-client.mjs
 * Input:  lib/client.cjs  (CJS bundle from esbuild)
 * Output: lib/client.js   (wrapped __ModuleLoader__.load factory)
 */

import { readFileSync, writeFileSync, unlinkSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const inputPath = join(root, 'lib', 'client.cjs')
const outputPath = join(root, 'lib', 'client.js')
const PLUGIN_ID = 'dsh-skin-avemujika'

const raw = readFileSync(inputPath, 'utf-8')

// The CJS bundle from esbuild assigns to module.exports. We place the
// entire bundle body inside the DSH factory function, where `module` and
// `exports` are pre-defined, so the bundle's assignments land on the
// factory's module.exports and get returned to the module loader.
const wrapped = `/* AUTO-GENERATED by scripts/wrap-client.mjs — do not edit by hand */
window.__ModuleLoader__.load({
  id: ${JSON.stringify(PLUGIN_ID)},
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
    var __DSH_SKIN_ID__ = ${JSON.stringify(PLUGIN_ID)};
    (function () {
${raw}
    }).call(module.exports);
    return module.exports;
  }
});
`

writeFileSync(outputPath, wrapped, 'utf-8')
console.log(`[wrap-client] Input:  ${inputPath} (${raw.length} bytes)`)
console.log(`[wrap-client] Output: ${outputPath} (${wrapped.length} bytes)`)

// Clean up intermediate CJS bundle — only the wrapped client.js is needed
try {
  unlinkSync(inputPath)
  console.log(`[wrap-client] Cleaned up intermediate: ${inputPath}`)
} catch {
  /* non-fatal */
}
